CREATE SCHEMA EVENTO_DB;

DROP DATABASE EVENTO_DB;

USE EVENTO_DB;

CREATE TABLE IF NOT EXISTS LOCAIS (
	LOCAL_ID INT PRIMARY KEY,
    LOCAL_NOME VARCHAR(100) NOT NULL,
    LOCAL_LOG VARCHAR(100) NOT NULL,
    LOCAL_NUMLOG INT,
    LOCAL_BAIRRO VARCHAR(100) NOT NULL,
    LOCAL_CIDADE VARCHAR(100) NOT NULL,
    LOCAL_UF CHAR(2) NOT NULL,
    LOCAL_CEP VARCHAR(20) NOT NULL,
    LOCAL_CAPACIDADE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS EVENTOS (
	EVENTO_ID INT PRIMARY KEY,
    EVENTO_NOME VARCHAR(20) NOT NULL,
    EVENTO_DATA DATE NOT NULL,
    EVENTO_ENTIDADE VARCHAR(20) NOT NULL,
    EVENTO_LOCAL INT
);

CREATE TABLE IF NOT EXISTS ATIVIDADES (
	ATIV_ID INT PRIMARY KEY,
    ATIV_NOME VARCHAR(100) NOT NULL,
    ATIV_DATA DATE NOT NULL,
    ATIV_HORA TIME NOT NULL,
    ATIV_EVENTO INT NOT NULL,
    CONSTRAINT FK_EVENTOS FOREIGN KEY(ATIV_EVENTO) REFERENCES EVENTOS(EVENTO_ID)
);

CREATE TABLE IF NOT EXISTS PARTICIPANTES (
	PART_NUMINSCRI INT NOT NULL,
    PART_CPF VARCHAR(20) NOT NULL,
	PRIMARY KEY(PART_NUMINSCRI, PART_CPF),
	PART_DATANASC DATE NOT NULL,
    PART_EMPRESA VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS PARTICIPANTE_ATIVIDADE (
	PART_NUMINSCRI INT NOT NULL,
    PART_CPF VARCHAR(20) NOT NULL,
    ATIV_ID INT NOT NULL,
    PRIMARY KEY(PART_NUMINSCRI, PART_CPF,ATIV_ID),
    CONSTRAINT PAAT_FK_PARTICIPANTES FOREIGN KEY(PART_NUMINSCRI, PART_CPF) REFERENCES PARTICIPANTES(PART_NUMINSCRI, PART_CPF),
    CONSTRAINT PAAT_FK_ATIVIDADES FOREIGN KEY(ATIV_ID) REFERENCES ATIVIDADES(ATIV_ID)
);

CREATE TABLE IF NOT EXISTS PARTICIPANTE_ATIVIDADE (
	PART_NUMINSCRI INT NOT NULL,
    PART_CPF VARCHAR(20) NOT NULL,
    EVENTO_ID INT NOT NULL,
    PRIMARY KEY(PART_NUMINSCRI, PART_CPF, EVENTO_ID),
    CONSTRAINT PAAT_FK_PARTICIPANTE FOREIGN KEY(PART_NUMINSCRI, PART_CPF) REFERENCES PARTICIPANTES(PART_NUMINSCRI, PART_CPF),
    CONSTRAINT PAAT_FK_EVENTOS FOREIGN KEY(EVENTO_ID) REFERENCES EVENTOS(EVENTO_ID)
);


CREATE SCHEMA REDESOCIAL_DB;

DROP DATABASE REDESOCIAL_DB;

USE REDESOCIAL_DB;

CREATE TABLE IF NOT EXISTS COMENTARIOS (
	COM_ID INT PRIMARY KEY,
    COM_TEXTO TEXT NOT NULL,
    COM_DATAHORA DATETIME NOT NULL,
    COM_USUARIO INT NOT NULL,
    COM_POST INT NOT NULL,
    CONSTRAINT FK_POSTAGENS FOREIGN KEY(COM_POST) REFERENCES POSTAGENS(POST_ID),
    CONSTRAINT FK_USUARIOS FOREIGN KEY(USU_ID) REFERENCES POSTAGENS(USU_ID)
);

CREATE TABLE IF NOT EXISTS POSTAGENS (
	POST_ID INT PRIMARY KEY,
    POST_TEXTO TEXT,
    POST_IMG BLOB,
    POST_DATAHORA DATETIME NOT NULL,
    POST_USUARIO INT NOT NULL,
    CONSTRAINT FK_USUARIOS FOREIGN KEY(POST_USUARIO) REFERENCES USUARIOS(USU_ID)
);

CREATE TABLE IF NOT EXISTS USUARIOS (
	USU_ID INT PRIMARY KEY,
    USU_NOME VARCHAR(100) NOT NULL,
    USU_SOBRENOME VARCHAR(100) NOT NULL,
    USU_EMAIL VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS GRUPOS (
	GRU_ID INT PRIMARY KEY,
    GRU_NOME VARCHAR(100) NOT NULL,
    GRU_DESCRICAO TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SEGUIDORES_USUARIOS (
	USUARIO INT NOT NULL,
    SEGUIDOR INT NOT NULL,
    primary key(USUARIO, SEGUIDOR),
    CONSTRAINT FK_USUARIO_SEGUIDOR FOREIGN KEY(USUARIO, SEGUIDOR) REFERENCES USUARIOS(USU_ID)
);

CREATE TABLE IF NOT EXISTS USUARIOS_GRUPOS (
	USU_ID INT PRIMARY KEY,
    USU_NOME VARCHAR(100) NOT NULL,
    USU_SOBRENOME VARCHAR(100) NOT NULL,
    USU_EMAIL VARCHAR(20) NOT NULL
);






